### ISSUE TITLE
Placing Rechiseled blocks with a trowel deletes it

### ISSUE THREAD

**Issue by squimbo** [theendercore/Trowel#6]
The mod in question:
https://www.curseforge.com/minecraft/mc-mods/rechiseled

Using the trowel to place blocks from this mod seem to delete the trowel. The block gets placed, but the trowel goes missing for no apparent reason

Trowel 1.2.1-1.20
Rechiseled 1.1.5b-fabric-mc1.20

pls fix uwu

**Comment by annaleighsmith** [comment]
I have the same issue with 1.19.2

**Comment by theendercore** [comment]
This happens cuz the rechiseled mod overrides vanilla behaviors. There is a fix for this already, ill publish it soon. I'm just bust with other mods right now.

**Comment by squimbo** [comment]
Alright, thanks for the quick response :)

**Comment by theendercore** [comment]
I fixed it in the latest update

**Comment by 18lyokon** [comment]
Is it possible to get this fix in the 1.19.4 version of this mod? I am still having this issue and there are no other released versions of this mod that work with 1.19.4

**Comment by theendercore** [comment]
Short answer, no, I don't have time. Plus, all version older than 1.20 are unsupported. The only way I would even consider doing this, if someone who supports me on ko-fi would ask for it. Sorry, but I just don't have time for this.
